included:
  - YumemiTraining
  - YumemiTrainingTests
excluded:
analyzer_rules:
  - capture_variable
  - explicit_self
  - typesafe_array_init
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - attributes
  - closure_body_length
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - prefer_nimble
  - required_deinit
  # Deprecated
  - anyobject_protocol
  - inert_defer
  - unused_capture_list
